version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run:
          command: |
            cd ./packages/fuselage/
            ls -la
            yarn build-storybook
            mv storybook-static /tmp/

      - persist_to_workspace:
          root: /tmp/
          paths:
            - storybook-static

  loki:
    docker:
      - image: yukinying/chrome-headless:63.0.3230.2
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get update && sudo apt-get install -y yarn

      - run:
          command: |
            yarn --version
            yarn

      - run:
          command: |
            cd ./packages/fuselage
            cat package.json | sed s/\.docker/.app/ > package.json-new
            mv package.json-new package.json
            yarn loki test --verboseRenderer --requireReference --reactUri file:/tmp/storybook-static

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - loki:
          requires:
            - build
