version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run:
        command: |
            cd ~/repo/packages/fuselage
            yarn build-storybook
            mv .loki/current /tmp/loki/

      - persist_to_workspace:
          root: /tmp/
          paths:
            - loki

  loki:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          command: |
            cd ~/repo/packages/fuselage
            cat package.json | sed s/\.docker/.app/ > package.json-new
            mv package.json-new package.json
            yarn loki test --verboseRenderer --requireReference --reactUri file:./storybook-static
