version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - setup_remote_docker
      - run:
          command: |
            yarn build-storybook
            yarn loki test --verboseRenderer --requireReference --reactUri file:./storybook-static
          working_directory: ~/repo/packages/fuselage
