version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run: yarn test
  build_and_deploy_storybook:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build-storybook
      - run: yarn deploy-storybook
workflows:
  version: 2
  build:
    jobs:
      - build
      - build_and_deploy_storybook:
          filters:
            branches:
              only: master
          requires:
            - build

