version: 2
jobs:
  build:
    docker:
      - image: zenika/alpine-chrome:with-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run:
          command: |
            cd ./packages/fuselage/
            ls -la
            yarn build-storybook
            cat package.json | sed s/\.docker/.app/ > package.json-new
            mv package.json-new package.json
            yarn loki test --verboseRenderer --chromeDockerImage=zenika/alpine-chrome:73 --requireReference --reactUri file:./storybook-static
