version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run: yarn test

      - run:
        command: yarn storybook
        working_directory: ~/repo/packages/fuselage
        background: true

      - run: sleep 5

      - run:
        command: yarn loki test
        working_directory: ~/repo/packages/fuselage
